Repository kokkos/kokkos-core-wiki, pull requests merged in 2025-03, with the labels that each got.

#639 update simd documentation for kokkos 4.6
  docs/source/API/simd/simd.md
  docs/source/API/simd/simd_mask.md
  docs/source/API/simd/where_expression.md
  docs/source/ProgrammingGuide/SIMD.md
Labels: Required for upcoming release

#636 Specify that nested `*MDRange` policies are limited to a sum reduction
  docs/source/API/core/parallel-dispatch/parallel_reduce.rst
  docs/source/API/core/policies/TeamThreadMDRange.rst
  docs/source/API/core/policies/TeamVectorMDRange.rst
  docs/source/API/core/policies/ThreadVectorMDRange.rst
Labels: enhancement

#646 Add initial MultiGPU documentation
  docs/source/API/core-index.rst
  docs/source/API/core/MultiGPUSupport.rst
Labels: documentation, Required for upcoming release

#620 Document SYCL backend behavior with no selected GPU architecture
  docs/source/API/core/execution_spaces.rst
  docs/source/get-started/configuration-guide.rst
Labels: Required for upcoming release
